### PR TITLE
Fix UserQuery to allow non-nil queries to succeed, and allow the return of OneLogin profile pictures

### PR DESCRIPTION
**Pull request by GraniteJV**

### CODE REVIEW

**Comment by dcaponi** [comment]
@GraniteJV thanks for your patience on this. Can you please move your logout call to a v1 service (e.g. `pkg/services/users/v1.go`) We're keeping v1 and v2 endpoints separate so we can remove v1 code if/when we deprecate the v1 endpoint. 

There also appears to be a merge conflict here. Would you mind addressing that too please.

FYI There is another PR open to make the time fields pointers (nullable). If its alright with you, I'd like to merge that and then you can focus on the v1 logout function. What do you think?

**Comment by ZsoltPath** [comment]
> 
> 
> @GraniteJV thanks for your patience on this. Can you please move your logout call to a v1 service (e.g. `pkg/services/users/v1.go`) We're keeping v1 and v2 endpoints separate so we can remove v1 code if/when we deprecate the v1 endpoint.
> 
> There also appears to be a merge conflict here. Would you mind addressing that too please.
> 
> FYI There is another PR open to make the time fields pointers (nullable). If its alright with you, I'd like to merge that and then you can focus on the v1 logout function. What do you think?

Hi @dcaponi,

Could you either this or #36 merge soon? 
It'd be nice to have the full search feature in terraform.

**Comment by dcaponi** [comment]
@ZsoltPath #36 is merged and a new release will be cut today. 

@GraniteJV I'm happy to merge your work that was not part of the other PR once you address the merge conflicts and bring in any new changes.

**Comment by bzvestey** [comment]
Closing this PR as it has conflicts and hasn't been updated in over 6 months

**Pull request closed without merging**
